import { Metadata } from "next"


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export const metadata:Metadata = {
  title: {
    absolute:"",
    default:"Nextjs Pro - Sam", 
    template:"%s | Sam"
  }
  // title.default property is useful when we want to provide fallback title for child route segment where they dont explicitly specify a title

  // title.template property is useful to create Dynamic Titles by adding a prefix or a suffix we can use title.template, this property applies to child route segments and  not the segment in which it is defined , this can be defined as %s

  // title.absolute - if we want to provide a title that completely ignores title.template set in the parent segment 
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:'lightblue',padding:'1rem'}}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{backgroundColor:'ghostwhite',padding:'1rem'}}>
        <p>Footer</p>
        </footer>
        </body>
    </html>
  )
}
